### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by emersion** [voldyman/MarkMyWords#11]
Just opening an issue about this feature. Do you know how to convert a `WebkitView` to PDF? I wasn't able to find how to achieve that.

Seems that we could use `get_snapshot()` (http://www.valadoc.org/#!api=webkit2gtk-4.0/WebKit.WebView.get_snapshot), but the pdf would be an image, not text.

Another approach would be to use the `print` function in `WebkitView` and automatically select the right printer (_Print to file_).

Any other ideas?

**Comment by voldyman** [comment]
I was thinking of implementing the Gtk.PrintOperation for the html doc and use pango to render the html.

something similar to footnote

http://bazaar.launchpad.net/~elementary-apps/footnote/footnote/view/head:/src/Widgets/CustomPrint.vala

**Comment by emersion** [comment]
Seems a good idea :-)

I can make a PR with that if you want, or do you prefer doing that yourself?

**Comment by emersion** [comment]
I'm working on it

**Comment by emersion** [comment]
See #16

**Comment by emersion** [comment]
Fixed in #16 :-)
