### ISSUE TITLE
YAML Support

### ISSUE THREAD

**Issue by TaylanTatli** [voldyman/MarkMyWords#12]
Can you add yaml support for Jekyll blog users. So we can write our blog posts with this app. Thanks. :)

**Comment by emersion** [comment]
Are you talking about this? http://jekyllrb.com/docs/frontmatter/

**Comment by TaylanTatli** [comment]
Yes.

**Comment by emersion** [comment]
Working on it ;-)

**Comment by TaylanTatli** [comment]
Thanks. :)
