### ISSUE TITLE
CSS stylesheet

### ISSUE THREAD

**Issue by emersion** [voldyman/MarkMyWords#20]
Add a CSS stylesheet when rendering

**Comment by voldyman** [comment]
What elements need to by styled?

**Comment by emersion** [comment]
Actually, it's no element needs to be styled (apart from tables maybe, haven't tested yet...). I suggest to use a stylesheet to have a nicer rendering look, e.g. we could use something like this: https://github.com/sindresorhus/github-markdown-css

There are tons of CSS stylesheets for Markdown export available on the Internet, we could even choose one for the dark Gtk theme. The best approach would be to add am entry for this in a preferences dialog, but I guess this will come later.

**Comment by emersion** [comment]
We could add page margins too!

**Comment by emersion** [comment]
Fixed in #21.
