### ISSUE TITLE
Can't compile in Fedora 21

### ISSUE THREAD

**Issue by Algram** [voldyman/MarkMyWords#34]
Hello, when I try to compile your awesome piece of art in Fedora 21, I get the following Error:
```
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr ../MarkMyWords/
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
CMake Error at CMakeLists.txt:1 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
```

Thank you very much!

**Comment by voldyman** [comment]
you need to install, valac 0.26 or greater, libgtk+-3.0-dev, g++ and build-essentials (or what ever is fedora's version of it)

basically you are just missing the required programs to build MarkMyWords.

**Comment by Algram** [comment]
Oh, yeah I installed a few packages and it built successfully now.
When I try to start I get this error, though:
```
./mark-my-words 

(mark-my-words:12469): GLib-GIO-ERROR **: Settings schema 'org.markmywords.settings' is not installed

Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)
```

**Comment by voldyman** [comment]
you have to do `sudo make install` as the schema needs to be installed in the system.

It can be done alternatively by copying the schema from `MarkMyWords/schema/org.markmywords.gschema.xml` to `/usr/share/glib-2.0/schemas/` and then executing

`sudo  glib-compile-schemas /usr/share/glib-2.0/schemas/`

**Comment by Algram** [comment]
I'm so derpy today. Of course that did it! Thank you very much! :)

**Comment by voldyman** [comment]
your welcome, i really hope someone helps me setup packaging for fedora.
