### ISSUE TITLE
Don't use the stock Scratch icon

### ISSUE THREAD

**Issue by Philip-Scott** [voldyman/MarkMyWords#47]
First of all, awesome app! :) But you should really avoid using the default Scratch icon on your app. By just looking at the icons, it can be confusing to distinguish you app from the default text editor in elementary.

**Comment by voldyman** [comment]
The default text editor icon was just supposed to be a place holder.
I have asked @snwh to make an icon.

**Comment by Philip-Scott** [comment]
Yup, i figured it was only a place holder, but it's still currently a "bug" ;) But hey, how would you like the icon? I could give it a try at making one if you wish

**Comment by voldyman** [comment]
I haven't given it much thought.
How about a window (rectangle with a distinguishable header bar) and some markdown written in it.

Very open to suggestions though.

**Comment by adiultra** [comment]
Just created a few icons hope you like it 
If you like them just reply and i will upload my svg files tooo.
![g1](https://cloud.githubusercontent.com/assets/12121575/8511612/14ed2d06-233e-11e5-8bdb-ebfa1e51215a.png)


I prefer the 1st Icon

**Comment by adiultra** [comment]
Another one :smile: 
![path16](https://cloud.githubusercontent.com/assets/12121575/8511631/2d7577f6-233f-11e5-813f-96bad891803f.png)

**Comment by voldyman** [comment]
yup, 1st one is good, i am going to go with that one. can i have the high resolution one? maybe with a bluish background?

btw can i have your contact information, a friend was looking for contractor for design work

**Comment by adiultra** [comment]
And another one
![g12](https://cloud.githubusercontent.com/assets/12121575/8511656/c5b2c6c6-2340-11e5-9207-4ab0e6375a99.png)

**Comment by adiultra** [comment]
And one more
![g129](https://cloud.githubusercontent.com/assets/12121575/8511691/60a2a228-2341-11e5-9e71-59260f6c104f.png)

**Comment by adiultra** [comment]
Is there color in the universe
![g123](https://cloud.githubusercontent.com/assets/12121575/8511764/7edfe61e-2342-11e5-8c71-20fa013c3ddb.png)

**Comment by voldyman** [comment]
The third one from the left(bluish)
Bigger image. I'll push the update asap

**Comment by adiultra** [comment]
Incomming....
https://mega.nz/#!hMpXXQya

itz a zip archive with the icons 

heres a higher res one

![256x256](https://cloud.githubusercontent.com/assets/12121575/8511911/24351a1c-2348-11e5-82d1-731656d70cc6.png)

**Comment by adiultra** [comment]
you migh want the blue darker isn't it ??

**Comment by adiultra** [comment]
whoops it needed a decryted key link 
Here's the one
https://mega.nz/#!hMpXXQya!54vngDB_7-ZZQU9eI5axXYyYnK_43naaaCoPLXyYHY4

**Comment by adiultra** [comment]
And here's the darker bluer one 
https://mega.nz/#!1FY3Fa7D!QHasUbcfwYeIKVxMgueReEp9fqu4RcazuuxzViY5gbw

![512x512](https://cloud.githubusercontent.com/assets/12121575/8511926/7ad40cb0-2349-11e5-8d83-a71a7e27d40a.png)

**Comment by voldyman** [comment]
can we have a single color, i.e. remove the purple and use blue only, a gradient to add depth (if that is the correct description)

**Comment by adiultra** [comment]
OK
Incoming ..
https://mega.nz/#!pZxnnDRL!vpkwlAQ-zA4eJ65hslFEOgxsNmFFyxi7vIpE1WQUn90

![256x256](https://cloud.githubusercontent.com/assets/12121575/8512243/3aca6402-2358-11e5-8d14-7c71a8e9ee5e.png)

**Comment by dar5hak** [comment]
@adiultra Excellent work, mate! Also, please make sure it follows the [elementary HIG](https://elementary.io/docs/human-interface-guidelines#icons), just like the rest of the app.

**Comment by adiultra** [comment]
I will try me best Bro

**Comment by adiultra** [comment]
What's it now
![nnhhhh](https://cloud.githubusercontent.com/assets/12121575/8528224/65f4a0de-242f-11e5-8aa6-4b6709f50a39.png)

**Comment by adiultra** [comment]
![weqdwesd](https://cloud.githubusercontent.com/assets/12121575/8528537/188855f0-2431-11e5-8c91-b79b8d6fcdd0.png)
This is my best shot dude just elemental

**Comment by voldyman** [comment]
Amazing work, I just am trying to make time to edit the code. The there is
a reason I haven't been pushing regular updates.

**Comment by voldyman** [comment]
can i get an svg for this file https://cloud.githubusercontent.com/assets/12121575/8528537/188855f0-2431-11e5-8c91-b79b8d6fcdd0.png ?

**Comment by adiultra** [comment]
yep here it is https://mega.nz/#!EUpUFKTa!JHO8fxzUEGADW6lqAIXUcG25lK4xSGdpi_Z_L7MVvmU


And i just adjusted a little bit with the system software installer icon
https://mega.nz/#!Fc40zRSK!1eLTL4eF-FJ-QbiS2o8-fBHJI84Vtbf9PD-jI03DF-0

**Comment by adiultra** [comment]
And of course I am trying to create other sized svg's as HIG states to use border of only one pixel per Icon Size

**Comment by voldyman** [comment]
pushed.
