### ISSUE TITLE
Solarized themes appear twice

### ISSUE THREAD

**Issue by orschiro** [voldyman/MarkMyWords#59]
Hi @voldyman and others, 

What a great and simple Markdown editor you created!

I just noticed a small bug:

![image](https://cloud.githubusercontent.com/assets/170947/8510939/04db7b76-2301-11e5-9234-f5ec2eb3ff2b.png)

The solarized themes should not appear twice, should net?

Thankfully,

Robert

**Comment by voldyman** [comment]
thanks for reporting the bug, i was working on the new UI for preferences but it's not complete, as soon as i have some free time, i'll finish it.

**Comment by orschiro** [comment]
That's great to hear. Thanks for your work!

**Comment by voldyman** [comment]
can you confirm that the bug still exists?

**Comment by orschiro** [comment]
@voldyman 

Yes, it is fixed. Thank you!
