### ISSUE TITLE
support for old GTK+ version

### ISSUE THREAD

**Issue by NaWer** [voldyman/MarkMyWords#60]
On Ubuntu 14.04 :
```
(mark-my-words:19654): Gtk-ERROR **: failed to add UI: <resource>/com/voldyman/markmywords/ui/headerbar.ui: required gtk+ version 3.12, current version is 3.10
```

**Comment by voldyman** [comment]
can you build and verify that the branch gtk-3.10 works for you? if so then i will pull it into the master branch

**Comment by NaWer** [comment]
I've tried with `version="3.10"` :
```
 (mark-my-words:24933): Gtk-ERROR **: failed to add UI: <resource>/com/voldyman/markmywords/ui/headerbar.ui:2:217 <object> requires attribute "id"
```

**Comment by NaWer** [comment]
Fixed here : https://github.com/voldyman/MarkMyWords/pull/64
Maybe you want to change id before merging ;)

**Comment by voldyman** [comment]
can you apply this diff and then i can merge your branch 
http://pastie.org/10302171

**Comment by NaWer** [comment]
I've just change the second newFileIcon to openFileIcon

**Comment by voldyman** [comment]
thanks!
merged, please verify so i can close the issue

**Comment by NaWer** [comment]
gtk-3.10 branch is running :)
I've just merge it to my master, updated with your last commits : icons on toolbar mode are still broken

**Comment by voldyman** [comment]
hmm, that is maybe because document-export & open-menu icons aren't in the default theme there. let me figure out a fix.

**Comment by NaWer** [comment]
After a quick look, my merge doesn't seems to be complete

**Comment by NaWer** [comment]
After another merge, I've got this (pushed in my master) :
![selection_001](https://cloud.githubusercontent.com/assets/352868/8778476/8385112c-2efe-11e5-9ca3-efa0d9f5d1e1.png)

better but not perfect.

Other issues (gtk 3.10 related ?) : 
* close button in about dialog doesn't work... 
* PDF export is broken :  empty file (https://github.com/voldyman/MarkMyWords/issues/36)

**Comment by voldyman** [comment]
Close button issue is weird, I'll look into that.
The PDF export thing is something that I can't reproduce, maybe you can
help me fix it, do you use any language other than English in your system?

The icon I think I'll need to bundle since it isn't present on ubuntu's
default theme.

**Comment by NaWer** [comment]
I'll try my best but don't have much time currently.
I'm on Ubuntu 14.04 LTS in french.
The "gears" icons is here without toolbar :
![selection_002](https://cloud.githubusercontent.com/assets/352868/8780165/7e9c7eb2-2f07-11e5-98d6-8a90b43e9fb4.png)

**Comment by voldyman** [comment]
ok, fixed the icon issue in toolbar mode

**Comment by NaWer** [comment]
Are you going to merge gtk-3.10 branch into master ?

**Comment by voldyman** [comment]
merged with master, please test :hammer:

**Comment by NaWer** [comment]
It's running fine. I'll open a new bug for PDF and close button
