### ISSUE TITLE
Getting Error while cmake

### ISSUE THREAD

**Issue by saratonite** [voldyman/MarkMyWords#68]
this is my shell show
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr ../
-- checking for one of the modules 'webkit2gtk-4.0;webkit2gtk-3.0'
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:367 (message):
  None of the required 'webkit2gtk-4.0;webkit2gtk-3.0' found
Call Stack (most recent call first):
  CMakeLists.txt:34 (pkg_search_module)

-- Found Vala: /usr/bin/valac  
-- checking for a minimum Vala version of 0.26.0
--   found Vala, version 0.28.1
-- GSettings schemas will be installed locally.
-- GSettings shemas will be compiled.
-- GSettings schemas will be installed into /usr/share/glib-2.0/schemas/
-- Configuring incomplete, errors occurred!
See also "/home/sarath/Documents/Github/MarkMyWords/build/CMakeFiles/CMakeOutput.log".
sarath@matrix:~/Documents/Github/MarkMyWords/build$ vim CmakeOutput.log
sarath@matrix:~/Documents/Github/MarkMyWords/build$ make
make: *** No targets specified and no makefile found.  Stop.

**Comment by voldyman** [comment]
That is because MarkMyWords requires some libraries to build that are not available on your system.

Please install `webkit2gtk-3.0` or 4.0 which ever is available in your distro.
