### ISSUE TITLE
Installation from PPA not working

### ISSUE THREAD

**Issue by brejoc** [voldyman/MarkMyWords#80]
OS: elementary Loki

I've added the PPA `ppa:voldyman/markmywords` with the command `apt-add-repository ppa:voldyman/markmywords`. An `apt update` show this error message:
```
E: The repository 'http://ppa.launchpad.net/voldyman/markmywords/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
Installation of the package _mark-my-words_ is not possible without further tweaking.

**Comment by voldyman** [comment]
i just enabled builds for the missing Ubuntu versions, can you verify if you can now install it?

**Comment by brejoc** [comment]
Works! :+1:
