### ISSUE TITLE
PPA release file

### ISSUE THREAD

**Issue by rdelhougne** [voldyman/MarkMyWords#92]
Please add a release file for Ubuntu bionic to the PPA.

Thanks for the great work :)

**Comment by jbriales** [comment]
Any update here? Still not available for Ubuntu 18.04

**Comment by Mayccoll** [comment]
:hand:

**Comment by voldyman** [comment]
Sorry, this issue dropped off my priorities list due to other things. I'll pick it up when i have some free time.

**Comment by voldyman** [comment]
Fixed, builds should be available now
