### ISSUE TITLE
Build with vala 0.42.2

### ISSUE THREAD

**Issue by awissu** [voldyman/MarkMyWords#93]
`[   75s] /home/abuild/rpmbuild/BUILD/MarkMyWords-0.1.1/src/Widgets/Window.vala:12.5-12.30: error: Property `Window.current_file' with custom `get' accessor and/or `set' mutator cannot have `default' value`
More info: https://build.opensuse.org/public/build/X11:Pantheon:Apps/openSUSE_Tumbleweed/x86_64/markmywords/_log

**Comment by Huholoman** [comment]
Same problem here. Im running GTK 3.24.5-1.

**Comment by voldyman** [comment]
updated, should be fixed now. please reopen if the issue persists.
